packages: []

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: false
  lefthook: true
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true

blockExoticSubdeps: true
minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyExclude:
  - eslint-import-resolver-typescript
  - semver
  - undici-types
